export default {
	login: "fsuh",
	id: 92304761,
	node_id: "U_kgDOBYB1eQ",
	avatar_url: "https://avatars.githubusercontent.com/u/92304761?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/fsuh",
	html_url: "https://github.com/fsuh",
	followers_url: "https://api.github.com/users/fsuh/followers",
	following_url: "https://api.github.com/users/fsuh/following{/other_user}",
	gists_url: "https://api.github.com/users/fsuh/gists{/gist_id}",
	starred_url: "https://api.github.com/users/fsuh/starred{/owner}{/repo}",
	subscriptions_url: "https://api.github.com/users/fsuh/subscriptions",
	organizations_url: "https://api.github.com/users/fsuh/orgs",
	repos_url: "https://api.github.com/users/fsuh/repos",
	events_url: "https://api.github.com/users/fsuh/events{/privacy}",
	received_events_url: "https://api.github.com/users/fsuh/received_events",
	type: "User",
	site_admin: false,
	name: "Fuh Suh",
	company: null,
	blog: "https://fsuh-deployed-projects.netlify.app/",
	location: "Helsinki",
	email: null,
	hireable: null,
	bio: "Full Stack Web Developer",
	twitter_username: null,
	public_repos: 50,
	public_gists: 0,
	followers: 9,
	following: 18,
	created_at: "2021-10-11T10:11:53Z",
	updated_at: "2023-12-29T23:55:22Z",
};
